String getPage() {
  String page = "";
  page += "HTTP/1.1 200 OK\r\n";
  page += "Content-Type: text/html\r\n\r\n";
  page += "<!DOCTYPE HTML>";
  page += "<html>";
  page += "<head>";
  page += "    <meta charset='UTF-8'>";
  page += "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
  page += "    <link href='https://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet'>";
  page += "    <link href='https://unpkg.com/nes.css/css/nes.min.css' rel='stylesheet'>";
  page += "    <style>";
  page += "      body { margin: 1rem; }";
  page += "      h1 > a, h1 > a:hover { color: inherit; text-decoration: none; }";
  page += "      .nes-container, .paragraph { margin-bottom: 1rem; }";
  page += "      #alarmTime:invalid { outline-color: #ce372b; box-shadow: 0 4px #e76e55, 0 -4px #e76e55, 4px 0 #e76e55, -4px 0 #e76e55; }";
  page += "    </style>";
  page += "</head>";
  page += "<body>";
  page += "    <header>";
  page += "      <h1><a href='/'>Puyotchi</a></h1>";
  page += "    </header>";
  page += "    <section class='nes-container with-title'>";
  page += "      <h2 class='title'>Status</h2>";
  page += "      <div>";
  page += "        <div class='paragraph'>";
  page += "          <label>Food</label>";
  page += "          <progress class='nes-progress is-error' value='food' max='10'></progress>";
  page += "        </div>";
  page += "        <div class='paragraph'>";
  page += "          <label>Sleep</label>";
  page += "          <progress class='nes-progress is-primary' value='sleep' max='20'></progress>";
  page += "        </div>";
  page += "      </div>";
  page += "    </section>";
  page += "    <section class='nes-container with-title'>";
  page += "      <h2 class='title'>Sequences</h2>";
  page += "      <div>";
  page += "        <a href='/happy'><button type='button' class='nes-btn'>Happy</button></a>";
  page += "        <a href='/unhappy'><button type='button' class='nes-btn'>Unhappy</button></a>";
  page += "        <a href='/ok'><button type='button' class='nes-btn'>Okay</button></a>";
  page += "        <a href='/no'><button type='button' class='nes-btn'>No</button></a>";
  page += "        <a href='/excited'><button type='button' class='nes-btn'>Excited</button></a>";
  page += "        <a href='/roll'><button type='button' class='nes-btn'>Roll</button></a>";
  page += "        <a href='/look'><button type='button' class='nes-btn'>Look</button></a>";
  page += "        <a href='/rain'><button type='button' class='nes-btn'>Rain</button></a>";
  page += "      </div>";
  page += "    </section>";
  page += "    <section class='nes-container with-title'>";
  page += "      <h2 class='title'>Alarm</h2>";
  page += "      <div>";
  page += "        <form method='GET' action='/alarm/set'>";
  page += "          <div class='paragraph nes-field'>";
  page += "            <label for='alarmTime'>Time</label>";
  page += "            <input type='text' name='alarmTime' id='alarmTime' value='00:00' class='nes-input' pattern='[0-9]{2}:[0-9]{2}'>";
  page += "          </div>";
  page += "          <div class='paragraph'>";
  page += "            <button type='submit' class='nes-btn is-primary'>Save</button>";
  page += "            <a href='/alarm/snooze'><button type='button' class='nes-btn is-error'>Snooze</button></a>";
  page += "          </div>";
  page += "        </form>";
  page += "        <div>";
  page += "          <label>";
  page += "            <input type='checkbox' class='nes-checkbox' id='alarmSetOn' onclick='location.href = \"/alarm/toggle\";'>";
  page += "            <span>Active</span>";
  page += "          </label>";
  page += "        </div>";
  page += "      </div>";
  page += "    </section>";
  page += "    <section class='nes-container with-title'>";
  page += "      <h2 class='title'>Settings</h2>";
  page += "      <div>";
  page += "        <div>";
  page += "          <label>";
  page += "            <input type='checkbox' class='nes-checkbox' id='mute' onclick='location.href = \"/mute/toggle\";'>";
  page += "            <span>Mute</span>";
  page += "          </label>";
  page += "        </div>";
  page += "        <div>";
  page += "          <label>";
  page += "            <input type='checkbox' class='nes-checkbox' id='automode' onclick='location.href = \"/automode/toggle\";'>";
  page += "            <span>Auto Mode</span>";
  page += "          </label>";
  page += "        </div>";
  page += "      </div>";
  page += "    </section>";
  // page += "<section class='nes-container with-title'>";
  // page += "  <h2 class='title'>Debug</h2>";
  // page += "  <div>";
  // page += "    <div>";
  // page += "      <label>isIdle</label>";
  // page += "      <span>isIdleValue</span>";
  // page += "    </div>";
  // page += "    <div>";
  // page += "      <label>isActionEvent</label>";
  // page += "      <span>isActionEventValue</span>";
  // page += "    </div>";
  // page += "    <div>";
  // page += "      <label>isRandomEvent</label>";
  // page += "      <span>isRandomEventValue</span>";
  // page += "    </div>";
  // page += "    <div>";
  // page += "      <label>eventInterval</label>";
  // page += "      <span>eventIntervalValue</span>";
  // page += "    </div>";
  // page += "    <div>";
  // page += "      <label>eventDuration</label>";
  // page += "      <span>eventDurationValue</span>";
  // page += "    </div>";
  // page += "  </div>";
  // page += "</section>";
  page += "</body>";
  page += "</html>";

  return page;
}
